---
title: "ggplot - bits and pieces"
author: "Matt Bixley"
date: "17 July 2017"
output:
  html_document:
    toc: yes
    toc_float: yes
geometry: margin=1in
fontsize: 12pt
subtitle: Mucking around with ggplot == LEARNING
---

```{r setup, include=F}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(ggthemes)
library(scales)
library(ggsci)
library(xkcd)


```

# Basic ggplot with cars

```{r}
data(mtcars)

gg <- ggplot(mtcars,aes(x=hp, y=mpg, colour=factor(cyl))) + geom_point()
gg
```

# ggplot Themes

https://github.com/jrnold/ggthemes


```{r, echo = T}
gg + theme_excel() + scale_colour_excel()
```

```{r, echo = T}
gg + theme_calc() + scale_color_calc()
```

```{r, echo = T}
gg + theme_gdocs() + scale_color_gdocs()
```

### Better Themes

```{r, echo = T}
gg + theme_economist() + scale_colour_economist() + scale_y_continuous(position = "right")
```
```{r, echo = T}
gg + theme_wsj() + scale_colour_wsj("colors6", "")
```

# Journal Themes

https://cran.r-project.org/web/packages/ggsci/vignettes/ggsci.html#introduction

Scientific Journal and Sci-Fi Themed Color Palettes for ggplot2

Nan Xiao <https://nanx.me> 
Miaozhu Li <http://miaozhu.li>


### Nature
```{r, echo = T}
gg + scale_color_npg() 
```

### Lancet
```{r, echo = T}
gg + scale_color_lancet()
```

### Journal of Clinical Oncology
```{r, echo = T}
gg + scale_color_jco()
```

### UCSC Genome Browser
```{r, echo = T}
gg + scale_color_ucscgb()
```

# ggThemeAssist

[ggThemeAssist](https://github.com/calligross/ggthemeassist)

https://github.com/calligross/ggthemeassist


```{r, eval=F,echo=T}
if (!requireNamespace("devtools", quietly = TRUE))
  install.packages("devtools")

devtools::install_github("calligross/ggthemeassist")
```


## Some Polling Data
https://en.wikipedia.org/wiki/Opinion_polling_for_the_New_Zealand_general_election,_2017

http://ellisp.github.io/

```{r, eval=T,echo=T}
poll <- read.table(file="polls.csv",header=T,sep=",")
tail(poll)

### make the plot data to long table first
pollplot <- poll %>% select(Order, Year, Month, National, Labour, Green, NZFirst) %>% 
  mutate(GL=Labour + Green, Date=paste0(Year,Month,"15")) %>% select(Order,Date,National,GL,NZFirst) %>% gather(key=Order,Date) 

colnames(pollplot) <- c("Order","Date","Party","Poll")

pollplot$Date <- as.Date(pollplot$Date,"%Y%B%d")
head(pollplot)

pollW <- poll %>% select(Order, Year, Month, National, Labour, Green, NZFirst) %>% 
  mutate(GLW=Labour + Green + NZFirst, NW = National + NZFirst, Date=paste0(Year,Month,"15")) %>% 
  select(Order,Date,NW,GLW) %>% gather(key=Order,Date) 

colnames(pollW) <- c("Order","Date","Party","Poll")

pollW$Date <- as.Date(pollW$Date,"%Y%B%d")
head(pollW)
```

```{r, eval=T,echo=T}

ww <- ggplot(data=pollW,aes(x=Date,y=Poll,colour=Party)) + 
  stat_smooth(formula = y ~ poly(x,5), method="glm", size=1,aes(weight=Date)) + 
  scale_color_manual(values=c("brown","blue")) +
  geom_point(position = position_jitter(width=0.1, height=0.1))

#ww

ww + theme(plot.subtitle = element_text(size = 12), 
    plot.caption = element_text(size = 12), 
    axis.ticks = element_line(colour = "gray15", 
        size = 0.9), axis.title = element_text(family = "serif", 
        size = 20, face = "bold.italic"), 
    axis.text = element_text(family = "serif", 
        size = 15, colour = "gray4", angle = 30), 
    plot.title = element_text(family = "serif", 
        size = 40, face = "bold", hjust = 0.5), 
    plot.background = element_rect(linetype = "dotdash"), 
    legend.direction = "horizontal") +labs(title = "The Polls", y = "Percent", 
    subtitle = "Winston will choose what Winston Chooses", 
    caption = "What could be worse? - The Trump")
```



# But Wait

There's More

### Set and forget

https://github.com/cttobin/ggthemr

### Save a theme

```{r, eval = F, echo =T}
theme_new <- function(base_size = 12, base_family = "Helvetica"){
    theme_bw(base_size = base_size, base_family = base_family) %+replace%
    theme(
        line = element_line(colour="black"),
        text = element_text(colour="black"),
        axis.title = element_text(size = 14),
        axis.text = element_text(colour="black", size=8),
        strip.text = element_text(size=12),
        legend.key=element_rect(colour=NA, fill =NA),
        panel.grid = element_blank(),   
        panel.border = element_rect(fill = NA, colour = "black", size=1),
        panel.background = element_rect(fill = "white", colour = "black"), 
        strip.background = element_rect(fill = NA)
        )
    }
```   



